name: release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy build
    - name: Make shared library and python package
      run: |
        make
    - name: Make release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.whl"
        token: ${{ secrets.RELEASE_TOKEN }}
